### ISSUE TITLE
Duplication issue with penal codes & attached criminal

### ISSUE THREAD

**Issue by Swompen** [Project-Sloth/ps-mdt#20]
![image](https://user-images.githubusercontent.com/16113909/163948738-2a52db39-130a-4734-9f33-8049e4b24fd1.png)

This image is a bad example for the penal codes, usually it's a perfect copy of all.
Sometimes when someone adds attached criminals, it will duplicate and all the penal codes as well sometimes, so a police officer adds lets say 3 penal codes and saves it, next day it will have 20x of each.

**Comment by MonkeyWhisper** [comment]
This was fixed on a previous PR

**Comment by Swompen** [comment]
> This was fixed on a previous PR

Dont agree, still have this issue and i got the latest files.

**Comment by MonkeyWhisper** [comment]
> > This was fixed on a previous PR
> 
> Dont agree, still have this issue and i got the latest files.

You don't need to agree, it was fixed as I'm not able to duplicate. If you need help, join Discord and ask for help.
